# Generated by Django 5.1.3 on 2024-11-14 06:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServerUptime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HostName', models.CharField(max_length=50)),
                ('HostIntIP', models.GenericIPAddressField()),
                ('BootTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('UpTime', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tblServerUptime',
            },
        ),
    ]
