# Generated by Django 5.1.3 on 2024-11-14 05:46

from django.db import migrations

def forwards_func(apps, schema_editor):
    CallTrends = apps.get_model("trends", "CallTrends")
    db_alias = schema_editor.connection.alias
    CallTrends.objects.using(db_alias).bulk_create(
        [
            CallTrends(Time='0:00:00', Calls='10', Abnd='2'),
            CallTrends(Time='0:05:00', Calls='25', Abnd='1'),
            CallTrends(Time='0:10:00', Calls='50', Abnd='5'),
            CallTrends(Time='0:15:00', Calls='5',  Abnd='0'),
            CallTrends(Time='0:20:00', Calls='15', Abnd='0'),
            CallTrends(Time='0:25:00', Calls='33', Abnd='3'),
            CallTrends(Time='0:30:00', Calls='20', Abnd='2'),
            CallTrends(Time='0:35:00', Calls='22', Abnd='1'),
            CallTrends(Time='0:40:00', Calls='50', Abnd='4'),
            CallTrends(Time='0:45:00', Calls='18', Abnd='2'),
            CallTrends(Time='0:50:00', Calls='24', Abnd='1'),
            CallTrends(Time='0:55:00', Calls='10', Abnd='0'),
            CallTrends(Time='1:00:00', Calls='15', Abnd='0'),
            CallTrends(Time='1:05:00', Calls='30', Abnd='3'),
            CallTrends(Time='1:10:00', Calls='45', Abnd='3'),
        ]        
    )
def reverse_func(apps, schema_editor):
    CallTrends = apps.get_model("uptime", "CallTrends")
    db_alias = schema_editor.connection.alias
    CallTrends.objects.using(db_alias).filter(Time='0:00:00', Calls='10', Abnd='2').delete()
    CallTrends.objects.using(db_alias).filter(Time='0:05:00', Calls='25', Abnd='1').delete()
    CallTrends.objects.using(db_alias).filter(Time='0:10:00', Calls='50', Abnd='5').delete()
    CallTrends.objects.using(db_alias).filter(Time='0:15:00', Calls='5', Abnd='0').delete()
    CallTrends.objects.using(db_alias).filter(Time='0:20:00', Calls='15', Abnd='0').delete()
    CallTrends.objects.using(db_alias).filter(Time='0:25:00', Calls='33', Abnd='3').delete()
    CallTrends.objects.using(db_alias).filter(Time='0:30:00', Calls='20', Abnd='2').delete()
    CallTrends.objects.using(db_alias).filter(Time='0:35:00', Calls='22', Abnd='1').delete()
    CallTrends.objects.using(db_alias).filter(Time='0:40:00', Calls='50', Abnd='4').delete()
    CallTrends.objects.using(db_alias).filter(Time='0:45:00', Calls='18', Abnd='2').delete()
    CallTrends.objects.using(db_alias).filter(Time='0:50:00', Calls='24', Abnd='1').delete()
    CallTrends.objects.using(db_alias).filter(Time='0:55:00', Calls='10', Abnd='0').delete()
    CallTrends.objects.using(db_alias).filter(Time='1:00:00', Calls='15', Abnd='0').delete()
    CallTrends.objects.using(db_alias).filter(Time='1:05:00', Calls='30', Abnd='3').delete()
    CallTrends.objects.using(db_alias).filter(Time='1:10:00', Calls='45', Abnd='3').delete()

class Migration(migrations.Migration):

    initial = True

    dependencies = [        
        ("trends", "0001_initial")
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
